/**
 * The campaign: 20 hand-authored levels (Act I 01-10, Act II 11-20).
 * Each level introduces at most one new mechanic, then remixes.
 * Act II tracks are deliberately longer (~1.5-2.5x Act I segment counts).
 */

import type { SegmentSpec } from './segments';

export interface LevelDef {
  id: string;
  index: number;
  biomeId: string;
  tips: string[];
  parTimeSec: number;
  segments: SegmentSpec[];
}

export const LEVELS: LevelDef[] = [
  {
    id: 'grid_zero',
    index: 0,
    biomeId: 'grid_zero',
    tips: ['hold W to accelerate - release to coast', 'SPACE jumps. small taps steer', 'follow the green edge glow'],
    parTimeSec: 75,
    segments: [
      { kind: 'platform', length: 18 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'platform', length: 8 },
      { kind: 'gap', length: 3 },
      { kind: 'platform', length: 12 },
      { kind: 'ramp', length: 10, rise: 2.5 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 12, width: 2 },
      { kind: 'gap', length: 3.5 },
      { kind: 'platform', length: 10 },
      { kind: 'spinners', length: 14, count: 1, speed: 1.1 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 10, dir: 1, width: 6 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'dune_sea',
    index: 1,
    biomeId: 'dune_sea',
    tips: ['sand traps kill your speed - jump through or boost around', 'wind shoves sideways: lean into it', 'momentum is everything downhill'],
    parTimeSec: 95,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'ramp', length: 12, rise: 3 },
      { kind: 'wind', length: 14, dirX: 1, strength: 12 },
      { kind: 'checkpoint' },
      { kind: 'dragZone', length: 10, strength: 2.8 },
      { kind: 'gap', length: 4 },
      { kind: 'curve', angle: 120, radius: 14, dir: -1, width: 7 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 16, count: 2, speed: 1.2 },
      { kind: 'dragZone', length: 8, strength: 2.8 },
      { kind: 'ramp', length: 12, rise: -4 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'checkpoint' },
      { kind: 'wind', length: 12, dirX: -1, strength: 15 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'neon_city',
    index: 2,
    biomeId: 'neon_city',
    tips: ['rooftop gaps are long - full speed or die', 'traffic platforms never wait. commit', 'thin beams: tap, never hold'],
    parTimeSec: 105,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gap', length: 4.5 },
      { kind: 'platform', length: 8 },
      { kind: 'gap', length: 5 },
      { kind: 'narrow', length: 14, width: 1.6 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 5, speed: 1, spacing: 6 },
      { kind: 'pistons', length: 14, count: 2, speed: 0.5 },
      { kind: 'checkpoint' },
      { kind: 'lasers', length: 16, count: 3, period: 2.4 },
      { kind: 'gap', length: 5.5 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'boost' },
      { kind: 'shards', pattern: 'arc', over: 8 },
      { kind: 'gap', length: 7 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 2, axis: 'x', distance: 7, speed: 1.3, spacing: 7 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'tide_break',
    index: 3,
    biomeId: 'tide_break',
    tips: ['lower gravity = floatier jumps. plan the landing', 'water drag pools kill momentum', 'geysers launch you - steer mid-air'],
    parTimeSec: 100,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'movers', count: 3, axis: 'y', distance: 2.4, speed: 0.8, spacing: 6 },
      { kind: 'checkpoint' },
      { kind: 'dragZone', length: 10, strength: 2.6 },
      { kind: 'bounces', count: 2, spacing: 8, power: 10 },
      { kind: 'gap', length: 6 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 12, dir: 1, width: 6 },
      { kind: 'movers', count: 2, axis: 'y', distance: 3, speed: 1.1, spacing: 7 },
      { kind: 'shards', pattern: 'arc', over: 8 },
      { kind: 'gap', length: 7 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'summit_pass',
    index: 4,
    biomeId: 'summit_pass',
    tips: ['ice sheets: near-zero friction. feather it', 'old tiles crumble half a second after you touch them', 'steep descents build dangerous speed'],
    parTimeSec: 110,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'ramp', length: 14, rise: 5 },
      { kind: 'slickZone', length: 12, width: 5 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 16, width: 1.8 },
      { kind: 'wind', length: 12, dirX: 1, strength: 14 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 16, tile: 2.6 },
      { kind: 'platform', length: 6 },
      { kind: 'ramp', length: 14, rise: -6 },
      { kind: 'shards', pattern: 'line', over: 12 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 100, radius: 11, dir: -1, width: 5 },
      { kind: 'slickZone', length: 10, width: 4 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'void_station',
    index: 5,
    biomeId: 'void_station',
    tips: ['LOW-G: jumps hang for seconds. aim the landing', 'inertia is king - brake early', 'GRAV-ANCHOR pulls you down when you need control'],
    parTimeSec: 120,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'gap', length: 9 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 0.7, spacing: 7 },
      { kind: 'spinners', length: 16, count: 2, speed: 0.9 },
      { kind: 'checkpoint' },
      { kind: 'gap', length: 8 },
      { kind: 'shards', pattern: 'arc', over: 9 },
      { kind: 'platform', length: 6 },
      { kind: 'gap', length: 10 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 2, axis: 'y', distance: 3, speed: 0.6, spacing: 8 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'magma_rift',
    index: 6,
    biomeId: 'magma_rift',
    tips: ['lava kills instantly. no exceptions', 'geysers launch you across the rift', 'basalt collapses - keep moving'],
    parTimeSec: 115,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'hazards', length: 14, count: 3 },
      { kind: 'checkpoint' },
      { kind: 'bounces', count: 3, spacing: 8, power: 12 },
      { kind: 'gap', length: 6 },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'checkpoint' },
      { kind: 'pistons', length: 14, count: 3, speed: 0.6 },
      { kind: 'gap', length: 5 },
      { kind: 'hazards', length: 12, count: 4 },
      { kind: 'shards', pattern: 'line', over: 9 },
      { kind: 'powerup', power: 'shield' },
      { kind: 'checkpoint' },
      { kind: 'bounces', count: 2, spacing: 9, power: 13 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'cryo_drift',
    index: 7,
    biomeId: 'cryo_drift',
    tips: ['near-zero friction: steer, never stop', 'banked curves hold your line if you carry speed', 'braking distance is a rumor'],
    parTimeSec: 110,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'slickZone', length: 14, width: 6 },
      { kind: 'curve', angle: 120, radius: 13, dir: 1, width: 6, bank: 0.3 },
      { kind: 'checkpoint' },
      { kind: 'sweepers', length: 16, count: 2, speed: 1 },
      { kind: 'slickZone', length: 12, width: 4 },
      { kind: 'shards', pattern: 'line', over: 12 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 14, count: 2, speed: 1.3 },
      { kind: 'curve', angle: 90, radius: 10, dir: -1, width: 5, bank: 0.35 },
      { kind: 'curve', angle: 90, radius: 10, dir: 1, width: 5, bank: 0.35 },
      { kind: 'checkpoint' },
      { kind: 'slickZone', length: 12, width: 3.4 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'overgrowth',
    index: 8,
    biomeId: 'overgrowth',
    tips: ['bounce caps rewrite your arc mid-flight', 'pendulum vines: watch one cycle, then go', 'half-pipes reward committed lines'],
    parTimeSec: 120,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'bounces', count: 3, spacing: 8, power: 11 },
      { kind: 'checkpoint' },
      { kind: 'halfpipe', length: 18, width: 7 },
      { kind: 'sweepers', length: 14, count: 2, speed: 1.4 },
      { kind: 'checkpoint' },
      { kind: 'gap', length: 5 },
      { kind: 'bounces', count: 2, spacing: 7, power: 12 },
      { kind: 'halfpipe', length: 16, width: 6 },
      { kind: 'shards', pattern: 'ring', over: 8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 110, radius: 12, dir: 1, width: 6 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'the_core',
    index: 9,
    biomeId: 'the_core',
    tips: ['shift gates flip gravity between gates', 'LOW-G: float. CRUSH: crawl. adapt instantly', 'everything you learned, all at once'],
    parTimeSec: 150,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gravityZone', length: 12, gravity: 3.2 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 6 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 14, count: 2, speed: 1.4 },
      { kind: 'gravityZone', length: 12, gravity: 12.5 },
      { kind: 'lasers', length: 12, count: 2, period: 2 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 1.1, spacing: 6.5 },
      { kind: 'checkpoint' },
      { kind: 'gravityZone', length: 10, gravity: 3.2 },
      { kind: 'gap', length: 9 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'shards', pattern: 'ring', over: 8 },
      { kind: 'pistons', length: 12, count: 2, speed: 0.7 },
      { kind: 'goal' },
    ],
  },

  // ================================================================== ACT II
  // 11 MIRROR MERE - gates + rings (timing intro)
  {
    id: 'mirror_mere',
    index: 10,
    biomeId: 'mirror_mere',
    tips: [
      'gates open on a beat - watch one cycle, then commit',
      'spinning rings: pass when the bar is vertical',
      'PHASE lets you ghost through lasers and crushers',
    ],
    parTimeSec: 145,
    segments: [
      { kind: 'platform', length: 16 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'platform', length: 10 },
      { kind: 'gates', length: 16, count: 2, period: 2.8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 12, dir: 1, width: 6 },
      { kind: 'platform', length: 10 },
      { kind: 'rings', length: 18, count: 2, speed: 1.3 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 14, width: 2.2 },
      { kind: 'gap', length: 4 },
      { kind: 'platform', length: 10 },
      { kind: 'powerup', power: 'phase' },
      { kind: 'lasers', length: 16, count: 3, period: 2.2 },
      { kind: 'checkpoint' },
      { kind: 'gates', length: 18, count: 3, period: 2.5 },
      { kind: 'shards', pattern: 'arc', over: 9 },
      { kind: 'gap', length: 5 },
      { kind: 'platform', length: 10 },
      { kind: 'rings', length: 16, count: 3, speed: 1.5 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 100, radius: 11, dir: -1, width: 5.5 },
      { kind: 'spinners', length: 14, count: 2, speed: 1.2 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 12 STORM SPIRE - conveyors + wind
  {
    id: 'storm_spire',
    index: 11,
    biomeId: 'storm_spire',
    tips: [
      'conveyors shove you forward - steer, do not fight',
      'crosswinds never stop: lean into the gust',
      'heavy air shortens jumps - commit earlier',
    ],
    parTimeSec: 155,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'ramp', length: 12, rise: 3 },
      { kind: 'conveyor', length: 14, strength: 16 },
      { kind: 'checkpoint' },
      { kind: 'wind', length: 16, dirX: 1, strength: 16 },
      { kind: 'gap', length: 4 },
      { kind: 'platform', length: 10 },
      { kind: 'curve', angle: 120, radius: 13, dir: -1, width: 6.5 },
      { kind: 'checkpoint' },
      { kind: 'conveyor', length: 16, strength: 20 },
      { kind: 'spinners', length: 14, count: 2, speed: 1.3 },
      { kind: 'wind', length: 14, dirX: -1, strength: 18 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 14, width: 2 },
      { kind: 'shards', pattern: 'line', over: 12 },
      { kind: 'powerup', power: 'boost' },
      { kind: 'gap', length: 5.5 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'conveyor', length: 12, strength: 22 },
      { kind: 'gates', length: 14, count: 2, period: 2.4 },
      { kind: 'wind', length: 12, dirX: 1, strength: 15 },
      { kind: 'ramp', length: 12, rise: -4 },
      { kind: 'sweepers', length: 14, count: 2, speed: 1.1 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 13 CHROME YARD - crushers + seesaws + dash
  {
    id: 'chrome_yard',
    index: 12,
    biomeId: 'chrome_yard',
    tips: [
      'crushers slam shut - wait for the open beat',
      'seesaws tip under you: stay centered or bail early',
      'DASH is a short forward burst through closing gaps',
    ],
    parTimeSec: 165,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'crushers', length: 16, count: 2, period: 2.4 },
      { kind: 'checkpoint' },
      { kind: 'seesaws', count: 2, spacing: 9, amp: 0.28, speed: 0.7 },
      { kind: 'platform', length: 8 },
      { kind: 'pistons', length: 14, count: 2, speed: 0.55 },
      { kind: 'checkpoint' },
      { kind: 'crushers', length: 18, count: 3, period: 2.1 },
      { kind: 'gap', length: 4 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'dash' },
      { kind: 'gates', length: 14, count: 2, period: 2.2 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 5.5, speed: 1.1, spacing: 6.5 },
      { kind: 'seesaws', count: 3, spacing: 8.5, amp: 0.34, speed: 0.85 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'shield' },
      { kind: 'crushers', length: 16, count: 3, period: 1.9 },
      { kind: 'spinners', length: 14, count: 2, speed: 1.4 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 11, dir: 1, width: 5.5 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 14 GLASS BLOOM - portals + slick + echo
  {
    id: 'glass_bloom',
    index: 13,
    biomeId: 'glass_bloom',
    tips: [
      'portals warp you across the void - roll into the cyan ring',
      'glass decks are slick: feather throttle on curves',
      'ECHO pulls shards from far away - greedy lines pay off',
    ],
    parTimeSec: 160,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'slickZone', length: 14, width: 5.5 },
      { kind: 'curve', angle: 100, radius: 12, dir: 1, width: 6, bank: 0.28 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 10 },
      { kind: 'platform', length: 10 },
      { kind: 'bounces', count: 3, spacing: 8, power: 11 },
      { kind: 'gap', length: 5 },
      { kind: 'checkpoint' },
      { kind: 'slickZone', length: 16, width: 4.5 },
      { kind: 'powerup', power: 'echo' },
      { kind: 'shards', pattern: 'ring', over: 10 },
      { kind: 'halfpipe', length: 18, width: 7 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 12 },
      { kind: 'rings', length: 14, count: 2, speed: 1.4 },
      { kind: 'slickZone', length: 12, width: 3.8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 10, dir: -1, width: 5, bank: 0.32 },
      { kind: 'shards', pattern: 'arc', over: 10 },
      { kind: 'gap', length: 6 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'magnet' },
      { kind: 'portal', gap: 11 },
      { kind: 'bounces', count: 2, spacing: 8, power: 12 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 15 SILENT ABYSS - crush gravity endurance
  {
    id: 'silent_abyss',
    index: 14,
    biomeId: 'silent_abyss',
    tips: [
      'crush gravity: jumps are short, landings are hard',
      'drag pools erase speed - jump the tar or boost through',
      'narrow decks punish floaty habits from earlier worlds',
    ],
    parTimeSec: 170,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'narrow', length: 14, width: 2.2 },
      { kind: 'gap', length: 3 },
      { kind: 'platform', length: 10 },
      { kind: 'checkpoint' },
      { kind: 'dragZone', length: 12, strength: 3.2 },
      { kind: 'spinners', length: 14, count: 2, speed: 1.1 },
      { kind: 'checkpoint' },
      { kind: 'ramp', length: 12, rise: 2.5 },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'crushers', length: 16, count: 2, period: 2.3 },
      { kind: 'dragZone', length: 10, strength: 3.5 },
      { kind: 'gap', length: 3.5 },
      { kind: 'platform', length: 10 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 16, width: 1.8 },
      { kind: 'pistons', length: 14, count: 3, speed: 0.5 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'boost' },
      { kind: 'conveyor', length: 12, strength: 14 },
      { kind: 'gates', length: 14, count: 2, period: 2.6 },
      { kind: 'dragZone', length: 10, strength: 3 },
      { kind: 'curve', angle: 90, radius: 12, dir: 1, width: 5.5 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 16 CLOCKWORK VEIL - interlocking timing gauntlet
  {
    id: 'clockwork_veil',
    index: 15,
    biomeId: 'clockwork_veil',
    tips: [
      'gates, rings, crushers share a rhythm - count the beat',
      'PHASE is a get-out-of-jail for one bad read',
      'do not sprint the openers; the closes are the real test',
    ],
    parTimeSec: 185,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'gates', length: 16, count: 2, period: 2.6 },
      { kind: 'rings', length: 14, count: 2, speed: 1.2 },
      { kind: 'checkpoint' },
      { kind: 'crushers', length: 16, count: 2, period: 2.4 },
      { kind: 'platform', length: 8 },
      { kind: 'spinners', length: 14, count: 2, speed: 1.3 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'phase' },
      { kind: 'gates', length: 18, count: 3, period: 2.3 },
      { kind: 'lasers', length: 14, count: 3, period: 2.1 },
      { kind: 'checkpoint' },
      { kind: 'seesaws', count: 2, spacing: 9, amp: 0.3, speed: 0.8 },
      { kind: 'rings', length: 16, count: 3, speed: 1.5 },
      { kind: 'shards', pattern: 'arc', over: 9 },
      { kind: 'checkpoint' },
      { kind: 'crushers', length: 18, count: 3, period: 2.0 },
      { kind: 'movers', count: 3, axis: 'x', distance: 5, speed: 1, spacing: 6.5 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'slow' },
      { kind: 'gates', length: 16, count: 3, period: 2.1 },
      { kind: 'rings', length: 14, count: 2, speed: 1.6 },
      { kind: 'sweepers', length: 14, count: 2, speed: 1.2 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 110, radius: 12, dir: -1, width: 5.5 },
      { kind: 'pistons', length: 12, count: 2, speed: 0.6 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 17 PRISM FALL - low-g aerial + portals + dash
  {
    id: 'prism_fall',
    index: 16,
    biomeId: 'prism_fall',
    tips: [
      'long hangs: aim the landing, do not panic-steer',
      'DASH mid-air extends your line across wide voids',
      'portals skip the worst empty air - trust the warp',
    ],
    parTimeSec: 175,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'dash' },
      { kind: 'gap', length: 9 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 14 },
      { kind: 'movers', count: 3, axis: 'y', distance: 2.8, speed: 0.7, spacing: 7 },
      { kind: 'checkpoint' },
      { kind: 'boosts', count: 2, spacing: 9 },
      { kind: 'gap', length: 8 },
      { kind: 'platform', length: 8 },
      { kind: 'rings', length: 16, count: 2, speed: 1.1 },
      { kind: 'checkpoint' },
      { kind: 'shards', pattern: 'arc', over: 12 },
      { kind: 'gap', length: 10 },
      { kind: 'platform', length: 6 },
      { kind: 'powerup', power: 'boost' },
      { kind: 'gap', length: 11 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 13 },
      { kind: 'halfpipe', length: 16, width: 6.5 },
      { kind: 'bounces', count: 2, spacing: 8, power: 10 },
      { kind: 'gap', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'movers', count: 2, axis: 'x', distance: 6, speed: 0.8, spacing: 7.5 },
      { kind: 'gap', length: 9 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 18 SOLAR FORGE - heat gauntlet
  {
    id: 'solar_forge',
    index: 17,
    biomeId: 'solar_forge',
    tips: [
      'lava still kills instantly - no exceptions',
      'crushers + hazards stack: SHIELD buys one mistake',
      'conveyors feed the fire: ride them, do not fight them',
    ],
    parTimeSec: 180,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'hazards', length: 14, count: 3 },
      { kind: 'checkpoint' },
      { kind: 'conveyor', length: 14, strength: 18 },
      { kind: 'crushers', length: 16, count: 2, period: 2.2 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'hazards', length: 12, count: 4 },
      { kind: 'powerup', power: 'shield' },
      { kind: 'checkpoint' },
      { kind: 'pistons', length: 14, count: 3, speed: 0.6 },
      { kind: 'bounces', count: 2, spacing: 8, power: 12 },
      { kind: 'gap', length: 5 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'phase' },
      { kind: 'lasers', length: 16, count: 3, period: 2 },
      { kind: 'hazards', length: 14, count: 4 },
      { kind: 'checkpoint' },
      { kind: 'conveyor', length: 12, strength: 20 },
      { kind: 'crushers', length: 16, count: 3, period: 1.95 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'falling', length: 12, tile: 2.6 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'dash' },
      { kind: 'gates', length: 14, count: 2, period: 2.2 },
      { kind: 'hazards', length: 12, count: 3 },
      { kind: 'spinners', length: 12, count: 2, speed: 1.4 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 19 NULL SIGNAL - near-void mastery
  {
    id: 'null_signal',
    index: 18,
    biomeId: 'null_signal',
    tips: [
      'near-void: jumps hang forever - GRAV-ANCHOR when you need floor',
      'rings and lasers in low-g are about patience, not panic',
      'DASH + portal chains cover the longest empty spans',
    ],
    parTimeSec: 190,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'gap', length: 9 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'gap', length: 11 },
      { kind: 'checkpoint' },
      { kind: 'rings', length: 16, count: 2, speed: 1.0 },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 0.65, spacing: 7.5 },
      { kind: 'checkpoint' },
      { kind: 'lasers', length: 16, count: 3, period: 2.4 },
      { kind: 'powerup', power: 'phase' },
      { kind: 'gap', length: 10 },
      { kind: 'platform', length: 6 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 16 },
      { kind: 'spinners', length: 16, count: 2, speed: 0.85 },
      { kind: 'shards', pattern: 'arc', over: 11 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'dash' },
      { kind: 'gap', length: 12 },
      { kind: 'platform', length: 6 },
      { kind: 'rings', length: 14, count: 3, speed: 1.2 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 2, axis: 'y', distance: 3.2, speed: 0.55, spacing: 8 },
      { kind: 'gap', length: 10 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'portal', gap: 14 },
      { kind: 'lasers', length: 14, count: 2, period: 2.2 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  // 20 EVENT HORIZON - finale: everything
  {
    id: 'event_horizon',
    index: 19,
    biomeId: 'event_horizon',
    tips: [
      'gravity flips without warning - read the zone glow',
      'every Act II tool is here: phase, dash, echo, portals',
      'this is the last orbit. finish it.',
    ],
    parTimeSec: 220,
    segments: [
      { kind: 'platform', length: 16 },
      { kind: 'gravityZone', length: 12, gravity: 3.0 },
      { kind: 'gap', length: 8 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'gates', length: 16, count: 2, period: 2.4 },
      { kind: 'rings', length: 14, count: 2, speed: 1.3 },
      { kind: 'checkpoint' },
      { kind: 'gravityZone', length: 12, gravity: 14.5 },
      { kind: 'crushers', length: 16, count: 2, period: 2.1 },
      { kind: 'dragZone', length: 10, strength: 2.8 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'phase' },
      { kind: 'lasers', length: 16, count: 3, period: 2 },
      { kind: 'conveyor', length: 12, strength: 18 },
      { kind: 'checkpoint' },
      { kind: 'portal', gap: 12 },
      { kind: 'seesaws', count: 2, spacing: 9, amp: 0.32, speed: 0.8 },
      { kind: 'shards', pattern: 'ring', over: 9 },
      { kind: 'checkpoint' },
      { kind: 'gravityZone', length: 10, gravity: 2.8 },
      { kind: 'powerup', power: 'dash' },
      { kind: 'gap', length: 11 },
      { kind: 'platform', length: 6 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 1.15, spacing: 6.5 },
      { kind: 'crushers', length: 14, count: 3, period: 1.9 },
      { kind: 'powerup', power: 'echo' },
      { kind: 'shards', pattern: 'arc', over: 10 },
      { kind: 'checkpoint' },
      { kind: 'gravityZone', length: 12, gravity: 15 },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'hazards', length: 12, count: 3 },
      { kind: 'checkpoint' },
      { kind: 'powerup', power: 'shield' },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'gravityZone', length: 10, gravity: 3.0 },
      { kind: 'portal', gap: 13 },
      { kind: 'rings', length: 14, count: 3, speed: 1.5 },
      { kind: 'spinners', length: 12, count: 2, speed: 1.4 },
      { kind: 'checkpoint' },
      { kind: 'boosts', count: 2, spacing: 8 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
];

export function getLevel(index: number): LevelDef | undefined {
  return LEVELS[index];
}

export function nextLevel(index: number): LevelDef | undefined {
  return LEVELS[index + 1];
}
