/**
 * The campaign: 10 hand-authored levels, one per biome.
 * Each level introduces at most one new mechanic, then remixes.
 */

import type { SegmentSpec } from './segments';

export interface LevelDef {
  id: string;
  index: number;
  biomeId: string;
  tips: string[];
  parTimeSec: number;
  segments: SegmentSpec[];
}

export const LEVELS: LevelDef[] = [
  {
    id: 'grid_zero',
    index: 0,
    biomeId: 'grid_zero',
    tips: ['hold W to accelerate - release to coast', 'SPACE jumps. small taps steer', 'follow the green edge glow'],
    parTimeSec: 75,
    segments: [
      { kind: 'platform', length: 18 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'platform', length: 8 },
      { kind: 'gap', length: 3 },
      { kind: 'platform', length: 12 },
      { kind: 'ramp', length: 10, rise: 2.5 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 12, width: 2 },
      { kind: 'gap', length: 3.5 },
      { kind: 'platform', length: 10 },
      { kind: 'spinners', length: 14, count: 1, speed: 1.1 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 10, dir: 1, width: 6 },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'dune_sea',
    index: 1,
    biomeId: 'dune_sea',
    tips: ['sand traps kill your speed - jump through or boost around', 'wind shoves sideways: lean into it', 'momentum is everything downhill'],
    parTimeSec: 95,
    segments: [
      { kind: 'platform', length: 14 },
      { kind: 'ramp', length: 12, rise: 3 },
      { kind: 'wind', length: 14, dirX: 1, strength: 12 },
      { kind: 'checkpoint' },
      { kind: 'dragZone', length: 10, strength: 2.8 },
      { kind: 'gap', length: 4 },
      { kind: 'curve', angle: 120, radius: 14, dir: -1, width: 7 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 16, count: 2, speed: 1.2 },
      { kind: 'dragZone', length: 8, strength: 2.8 },
      { kind: 'ramp', length: 12, rise: -4 },
      { kind: 'shards', pattern: 'line', over: 10 },
      { kind: 'checkpoint' },
      { kind: 'wind', length: 12, dirX: -1, strength: 15 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'neon_city',
    index: 2,
    biomeId: 'neon_city',
    tips: ['rooftop gaps are long - full speed or die', 'traffic platforms never wait. commit', 'thin beams: tap, never hold'],
    parTimeSec: 105,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gap', length: 4.5 },
      { kind: 'platform', length: 8 },
      { kind: 'gap', length: 5 },
      { kind: 'narrow', length: 14, width: 1.6 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 5, speed: 1, spacing: 6 },
      { kind: 'pistons', length: 14, count: 2, speed: 0.5 },
      { kind: 'checkpoint' },
      { kind: 'lasers', length: 16, count: 3, period: 2.4 },
      { kind: 'gap', length: 5.5 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'boost' },
      { kind: 'shards', pattern: 'arc', over: 8 },
      { kind: 'gap', length: 7 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 2, axis: 'x', distance: 7, speed: 1.3, spacing: 7 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'tide_break',
    index: 3,
    biomeId: 'tide_break',
    tips: ['lower gravity = floatier jumps. plan the landing', 'water drag pools kill momentum', 'geysers launch you - steer mid-air'],
    parTimeSec: 100,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'movers', count: 3, axis: 'y', distance: 2.4, speed: 0.8, spacing: 6 },
      { kind: 'checkpoint' },
      { kind: 'dragZone', length: 10, strength: 2.6 },
      { kind: 'bounces', count: 2, spacing: 8, power: 10 },
      { kind: 'gap', length: 6 },
      { kind: 'platform', length: 8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 90, radius: 12, dir: 1, width: 6 },
      { kind: 'movers', count: 2, axis: 'y', distance: 3, speed: 1.1, spacing: 7 },
      { kind: 'shards', pattern: 'arc', over: 8 },
      { kind: 'gap', length: 7 },
      { kind: 'checkpoint' },
      { kind: 'platform', length: 10 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'summit_pass',
    index: 4,
    biomeId: 'summit_pass',
    tips: ['ice sheets: near-zero friction. feather it', 'old tiles crumble half a second after you touch them', 'steep descents build dangerous speed'],
    parTimeSec: 110,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'ramp', length: 14, rise: 5 },
      { kind: 'slickZone', length: 12, width: 5 },
      { kind: 'checkpoint' },
      { kind: 'narrow', length: 16, width: 1.8 },
      { kind: 'wind', length: 12, dirX: 1, strength: 14 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 16, tile: 2.6 },
      { kind: 'platform', length: 6 },
      { kind: 'ramp', length: 14, rise: -6 },
      { kind: 'shards', pattern: 'line', over: 12 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 100, radius: 11, dir: -1, width: 5 },
      { kind: 'slickZone', length: 10, width: 4 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'void_station',
    index: 5,
    biomeId: 'void_station',
    tips: ['LOW-G: jumps hang for seconds. aim the landing', 'inertia is king - brake early', 'GRAV-ANCHOR pulls you down when you need control'],
    parTimeSec: 120,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 8 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'gap', length: 9 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 0.7, spacing: 7 },
      { kind: 'spinners', length: 16, count: 2, speed: 0.9 },
      { kind: 'checkpoint' },
      { kind: 'gap', length: 8 },
      { kind: 'shards', pattern: 'arc', over: 9 },
      { kind: 'platform', length: 6 },
      { kind: 'gap', length: 10 },
      { kind: 'checkpoint' },
      { kind: 'movers', count: 2, axis: 'y', distance: 3, speed: 0.6, spacing: 8 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'magma_rift',
    index: 6,
    biomeId: 'magma_rift',
    tips: ['lava kills instantly. no exceptions', 'geysers launch you across the rift', 'basalt collapses - keep moving'],
    parTimeSec: 115,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'hazards', length: 14, count: 3 },
      { kind: 'checkpoint' },
      { kind: 'bounces', count: 3, spacing: 8, power: 12 },
      { kind: 'gap', length: 6 },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'checkpoint' },
      { kind: 'pistons', length: 14, count: 3, speed: 0.6 },
      { kind: 'gap', length: 5 },
      { kind: 'hazards', length: 12, count: 4 },
      { kind: 'shards', pattern: 'line', over: 9 },
      { kind: 'powerup', power: 'shield' },
      { kind: 'checkpoint' },
      { kind: 'bounces', count: 2, spacing: 9, power: 13 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'cryo_drift',
    index: 7,
    biomeId: 'cryo_drift',
    tips: ['near-zero friction: steer, never stop', 'banked curves hold your line if you carry speed', 'braking distance is a rumor'],
    parTimeSec: 110,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'slickZone', length: 14, width: 6 },
      { kind: 'curve', angle: 120, radius: 13, dir: 1, width: 6, bank: 0.3 },
      { kind: 'checkpoint' },
      { kind: 'sweepers', length: 16, count: 2, speed: 1 },
      { kind: 'slickZone', length: 12, width: 4 },
      { kind: 'shards', pattern: 'line', over: 12 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 14, count: 2, speed: 1.3 },
      { kind: 'curve', angle: 90, radius: 10, dir: -1, width: 5, bank: 0.35 },
      { kind: 'curve', angle: 90, radius: 10, dir: 1, width: 5, bank: 0.35 },
      { kind: 'checkpoint' },
      { kind: 'slickZone', length: 12, width: 3.4 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'overgrowth',
    index: 8,
    biomeId: 'overgrowth',
    tips: ['bounce caps rewrite your arc mid-flight', 'pendulum vines: watch one cycle, then go', 'half-pipes reward committed lines'],
    parTimeSec: 120,
    segments: [
      { kind: 'platform', length: 10 },
      { kind: 'bounces', count: 3, spacing: 8, power: 11 },
      { kind: 'checkpoint' },
      { kind: 'halfpipe', length: 18, width: 7 },
      { kind: 'sweepers', length: 14, count: 2, speed: 1.4 },
      { kind: 'checkpoint' },
      { kind: 'gap', length: 5 },
      { kind: 'bounces', count: 2, spacing: 7, power: 12 },
      { kind: 'halfpipe', length: 16, width: 6 },
      { kind: 'shards', pattern: 'ring', over: 8 },
      { kind: 'checkpoint' },
      { kind: 'curve', angle: 110, radius: 12, dir: 1, width: 6 },
      { kind: 'goal' },
    ],
  },
  {
    id: 'the_core',
    index: 9,
    biomeId: 'the_core',
    tips: ['shift gates flip gravity between gates', 'LOW-G: float. CRUSH: crawl. adapt instantly', 'everything you learned, all at once'],
    parTimeSec: 150,
    segments: [
      { kind: 'platform', length: 12 },
      { kind: 'gravityZone', length: 12, gravity: 3.2 },
      { kind: 'gap', length: 7 },
      { kind: 'platform', length: 6 },
      { kind: 'checkpoint' },
      { kind: 'spinners', length: 14, count: 2, speed: 1.4 },
      { kind: 'gravityZone', length: 12, gravity: 12.5 },
      { kind: 'lasers', length: 12, count: 2, period: 2 },
      { kind: 'checkpoint' },
      { kind: 'falling', length: 14, tile: 2.6 },
      { kind: 'movers', count: 3, axis: 'x', distance: 6, speed: 1.1, spacing: 6.5 },
      { kind: 'checkpoint' },
      { kind: 'gravityZone', length: 10, gravity: 3.2 },
      { kind: 'gap', length: 9 },
      { kind: 'powerup', power: 'anchor' },
      { kind: 'shards', pattern: 'ring', over: 8 },
      { kind: 'pistons', length: 12, count: 2, speed: 0.7 },
      { kind: 'goal' },
    ],
  },
];

export function getLevel(index: number): LevelDef | undefined {
  return LEVELS[index];
}

export function nextLevel(index: number): LevelDef | undefined {
  return LEVELS[index + 1];
}
